apiVersion: apps/v1
kind: Deployment
metadata:
  name: ld-integ-stadt-zuerich-ch
spec:
  template:
    spec:
      containers:
        - name: ld-stadt-zuerich-ch
          image: registry.zazuko.com/docker/ld.stadt-zuerich.ch
          imagePullPolicy: Always
          env:
            - name: SPARQL_ENDPOINT_URL
              value: https://stardog-int.cluster.ldbar.ch/
            - name: SPARQL_ENDPOINT_USER
              valueFrom:
                secretKeyRef:
                  name: sparql-credentials-integ
                  key: password
            - name: SPARQL_ENDPOINT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparql-credentials-integ
                  key: password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /health
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              path: /health
              port: http
