default:
  image: ghcr.io/zazuko/deploy-image:v1.4
  tags:
    - kubernetes

stages:
  - build
  - deploy

# build Docker image
build:
  stage: build
  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - |
      executor \
        --context="$CI_PROJECT_DIR" \
        --dockerfile=Dockerfile \
        $(gitlab-docker-tag | sed "s|.*|--destination=${CI_REGISTRY_IMAGE}:&|") \
        --build-arg="BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
        --build-arg="COMMIT=$CI_COMMIT_SHA" \
        --destination="$CI_REGISTRY_IMAGE" \
        --target=production \
        --build-arg "VERSION=$CI_COMMIT_REF_SLUG"

# deploy to the Kubernetes cluster
deploy:
  stage: deploy
  only:
    - tags
  script:
    - cd k8s/
    - ensure-pull-secret
    - set-gitlab-annotations
    - kustomize edit set image "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - kustomize build | tee manifest.yaml
    - kubectl apply -f manifest.yaml
  environment:
    name: production
    kubernetes:
      namespace: ld-stadt-zuerich-ch
