default:
  image: ghcr.io/zazuko/deploy-image:v1.4
  tags:
    - kubernetes

stages:
  - build

# build Docker image
build:
  stage: build
  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - |
      executor \
        --context="$CI_PROJECT_DIR" \
        --dockerfile=Dockerfile \
        $(gitlab-docker-tag | sed "s|.*|--destination=${CI_REGISTRY_IMAGE}:&|") \
        --build-arg="BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
        --build-arg="COMMIT=$CI_COMMIT_SHA" \
        --destination="$CI_REGISTRY_IMAGE" \
        --target=production \
        --build-arg "VERSION=$CI_COMMIT_REF_SLUG"
