image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build_prod:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  only:
    - tags

build_integ:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:develop"
    - docker push "$CI_REGISTRY_IMAGE:develop"
  only:
    - master

deploy_prod:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack ssz-prod --service ld --new-image $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - tags

deploy_integ:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack ssz-integ --service ld --new-image $CI_REGISTRY_IMAGE:develop
  only:
    - master
