# examples http://localhost:9000/api/statistics/flaechen/R00091?from=1965&to=1987
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX ldprop: <http://ld.stadt-zuerich.ch/statistics/property/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT  {
      ?obs a qb:Observation .
      ?obs ?property ?value .
      ?value rdfs:label ?label .
      ?value skos:notation ?notation .
}
WHERE {
    # Specify Class
    ?obs a qb:Observation ;
       qb:dataSet <http://ld.stadt-zuerich.ch/statistics/table/BAU001> ;
       ?property ?value.
    # Get Labels and Notations
    OPTIONAL { ?value rdfs:label ?label .}
    OPTIONAL { ?value skos:notation ?notation .}

    # Specify properties
    ?obs <http://ld.stadt-zuerich.ch/statistics/property/ZEIT> ?zeit;
      <http://ld.stadt-zuerich.ch/statistics/property/RAUM> ?raum;
      <http://ld.stadt-zuerich.ch/statistics/property/KENNZAHL> ?kennzahl;
      <http://ld.stadt-zuerich.ch/statistics/property/BBA> ?bba.
  
    # Get Notations
    ?raum skos:notation ?raumNotation .
    ?bba skos:notation ?bbaNotation .
    ?kennzahl skos:notation ?kennzahlNotation .

    # Only because time is not yet clean bind.
    BIND (xsd:datetime(SUBSTR(str(?zeit),STRLEN(str(?zeit))-3)) AS ?zeitNotation)

    # Filter per Property
#    FILTER (?raumNotation IN("R00400"))
    FILTER (?bbaNotation IN("BBA3300"))

    # Filter per Property
    ${typeof raum !== 'undefined'? 'FILTER (?raumNotation IN (' + (raum.join ? raum.map(v => v.toCanonical()).join() : raum.toCanonical()) + '))' : ''}

    # Filter Time Range
    ${typeof from !== 'undefined'? 'FILTER (?zeitNotation >= xsd:datetime("'+from+'"))':''}
    ${typeof to !== 'undefined'? 'FILTER (?zeitNotation <= xsd:datetime("'+to+'"))':''}
} ORDER BY ?zeitNotation
